kind: pipeline
name: test

trigger:
  event:
    - push
    - pull_request
    - tag

workspace:
  base: /go
  path: src/github.com/shipt/${DRONE_REPO_NAME}

steps:
  - name: test
    image: golang:1.13
    commands:
      - go test -v -tags=integration -coverprofile=coverage.txt -covermode=atomic ./...
    environment:
      SERVICE_ENV: test
      CI_GITHUB_ACCESS_TOKEN:
        from_secret: github_token  
  - name: codecov
    image: plugins/codecov
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    files: coverage.txt  
  - name: docker-prep
    image: harbor.shipttech.com/plugins/dockerspec
    pull: always

  - name: docker-build-and-push
    image: plugins/docker
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    settings:
      build_args_from_env:
        - GITHUB_TOKEN
      registry: harbor.shipttech.com
      env_file: "docker_args"
